# Variables and lists.
######################################################################
HEADERS := \
	random.h
SOURCES := \
	random.cpp
OBJECTS := \
	out/random.o
UPDATES := out/ out/main.o $(OBJECTS) $(HEADERS)



# Commands.
######################################################################
main:  $(UPDATES)
	g++ -Wall out/main.o $(OBJECTS) -o main

out/main.o:  main.cpp
	g++ -Wall -c main.cpp -o out/main.o

out/random.o:  random.cpp random.h
	g++ -Wall -c random.cpp -o out/random.o

out/:
	mkdir -p out

run:  main
	./main

output:  main
	./main > output.txt

clean:
	rm -rf out main output.txt
